### ISSUE TITLE
[Question] Status deGardenServer

### ISSUE THREAD

**Issue by Tezzlicious** [gardena-smart-reverse-engineering/deGardenServer#2]
Hi SciLor,

Great findings about the Gardena gateway. I'm curious what the state of deGardenServer is at the moment. I have an extra bridge at hand and am thinking about rooting it. 

Is deGardenServer useable for my Smart Mower and Smart Water Control at its current state?

Thanks for your efforts.

tezzlicious

**Comment by Tezzlicious** [comment]
Rooting went well, but I'm struggling with setting everything up. Do I first need to register through the app to the cloud and then redirect it to deGardenServer? Thanks!

**Comment by BOFHELL** [comment]
interested in current state +1

**Comment by SciLor** [comment]
The deGardenaServer isn't able to replicate the Gardena servers at the moment. It is only a proof of concept that the server may be replacable. The problem is that the cloud gives everything readable names. On gateway side you would first need to reverse everything from zero.

The registration isn't needed. 

I won't be able to work on it in the future.

**Comment by Tezzlicious** [comment]
HI SciLor, thanks for the reply. I got the server running and saw indeed that the cloud gives everything IDs etc. If I understand correctly, everything would have to been mapped to deGardenaServer to make it work.

Do you happen to know if it possible to send commands directly to lemonbeat/device without taking the Cloud route? Basically direct commands to start and stop etc.

**Comment by SciLor** [comment]
@Tezzlicious I am pretty sure it would work. Just record the commands that are sent to the device when you send a command via the cloud and try to replicate it.
